apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: oauth-proxy
spec:
  hostnames:
  - radarr.yewolf.fr
  - sonarr.yewolf.fr
  - qbittorrent.yewolf.fr
  - bazarr.yewolf.fr
  - prowlarr.yewolf.fr
  - flaresolverr.yewolf.fr
  - bazarr.yewolf.fr
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: kgateway
    namespace: kgateway
    sectionName: https
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: ak-outpost-proxy
      port: 9000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /