apiVersion: v1
kind: Service
metadata:
  name: stalwart-primary
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: smtp-internal
    port: 2500
    targetPort: 2500
  - name: submission
    protocol: TCP
    port: 587
    targetPort: 587
  - name: smtps
    protocol: TCP
    port: 465
    targetPort: 465
  - name: imap
    protocol: TCP
    port: 143
    targetPort: 143
  - name: imaps
    protocol: TCP
    port: 993
    targetPort: 993
  - name: sieve
    protocol: TCP
    port: 4190
    targetPort: 4190
  selector:
    app: stalwart
    instance: primary
