apiVersion: apps/v1
kind: Deployment
metadata:
  name: satisfactory
  namespace: satisfactory
  labels:
    app: satisfactory
spec:
  replicas: 0
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      nodeSelector:
        location: home1
      tolerations:
        - key: "PrivateNode"
          operator: "Equal"
          value: "home1"
      containers:
        - name: satisfactory
          image: mirror.gcr.io/wolveix/satisfactory-server:latest@sha256:e103700ae6ae4c50f19dac80eadb2a805c5b885e179ae2a40850e967bf189efd
          imagePullPolicy: Always
          ports:
            - containerPort: 7777
              hostPort: 7777
              protocol: UDP
            - containerPort: 7777
              hostPort: 7777
              protocol: TCP
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
          env:
            - name: MAXPLAYERS
              value: "6"
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: ROOTLESS
              value: "false"
            - name: STEAMBETA
              value: "false"
          volumeMounts:
            - mountPath: /config
              name: config
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 2
              memory: 8Gi
      volumes:
        - name: config
          hostPath:
            path: /home/yewolf/containers/satisfactory/satisfactory-server
            type: Directory
