apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kgateway

resources:
- namespace.yaml
- gatewayparams.yaml
- gatewayclass.yaml
- gateway.yaml
- proxy-gatewayparams.yaml
- proxy-gatewayclass.yaml
- proxy-gateway.yaml
- http-to-https.yaml
- listener-policy.yaml
