apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfoliosh

resources:
- network-policy.yaml
- namespace.yaml
- deployment.yaml
- service.yaml
- gateway.yaml
- tcproute.yaml
- hostkey-sops.yaml
