apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mqtt

resources:
- namespace.yaml
- cert.yaml
- secret-sops.yaml
- repo.yaml
- release.yaml
- service.yaml
- listenerset.yaml
- tcproute.yaml
