apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant

resources:
- namespace.yaml
- local-service.yaml
- repo.yaml
- release.yaml
- route.yaml
- ./addons
- ./ai

- schedule.yaml
- ../../../../reusables/backup-secret