apiVersion: v1
kind: Secret
metadata:
    name: esphome-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:B490CyW7PygEhJ3BVMlQ5+ma2xvRTK/YBA3ulJaUyno=,iv:pF6rGEx5opG93U+LxyE64oP8z2wo1qYwMY0+GthCqRg=,tag:R4sVJ0gvYKaZtJv7yob13w==,type:str]
sops:
    lastmodified: "2025-12-01T21:12:24Z"
    mac: ENC[AES256_GCM,data:iD6hX7Vg4dlGcw3y6+6tk9EdlowC55w5xl3Ovnt5IiOmZhFDQnQnQOnHk3mbBn3L77Vq1mNT0zVOFlObc5tO9Ikb4KPy4l+LtdDM4fw3dML7l9oHBtqRQYQkWPqapVnt6BGPeCHHfQR5C4EumzSaGzI6XXatr1YHmg3wiScXSYo=,iv:QurUlMTtJsmOj6hb2rfTJznsPK7qJzMQSIVKjrVuXQ8=,tag:rKyUSyROZXwOvCeN+WBZhQ==,type:str]
    pgp:
        - created_at: "2025-12-01T21:12:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D6rJQTzBUCVESAQdAiNFCxwdFt8vhiDkVGAHqpZjQYeUEylQb/yj7HNjimxAw
            emGe9u9nNTXbEw4XnrpgC2RB2eUXkXmHWGNz/LKkbE2XEE2xeYhwAvPJg90dWdAC
            0l4BU6yrCWMK1fwqy0CGarvCvC+aNSgox/+JDXpLAukWREz1S89zqd1++PT2FoLl
            4MZrQ3dL1c1hsZkcgIPbTPM0T4YN/4h2cTICYEFsyNBPydENId3pH6JxpLDrA+b7
            =VFk8
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2025-12-01T21:12:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAgYnTXT9fZwcIGM5xedE6J7ieCHv6Ki+Q9cxqFLe18Wgw
            5Hi/afXAySC8dNCTLQqvN18Bgk8rWiOTXytvffucCJ92Qu0vjEy7CDX5AuOW/Qgt
            0l4BK39DovC4i+AoBeZSaYQtxPmep7E9O8vfyefY6OoQ9OPpyBZmGKgcLkXEqZ71
            Ww+MuUKjJPJ3tZ5qgqRwu3tHKKbMd+bZP+ANJH6gLVOGmKx7ois8QoQo/As8pdtq
            =L/MN
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.10.2
