apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  labels:
    app: roundcube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      containers:
        - name: roundcube
          image: mirror.gcr.io/roundcube/roundcubemail:latest@sha256:e007b9de55c2c38ae94057adca4c96915d20ec603c485cd46030546430fd4043
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: roundcube-env
          env:
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: "ssl://mail.yewolf.fr"
            - name: ROUNDCUBEMAIL_DEFAULT_PORT
              value: "993"
            - name: ROUNDCUBEMAIL_SMTP_SERVER
              value: "tls://mail.yewolf.fr"
            - name: ROUNDCUBEMAIL_SMTP_PORT
              value: "587"
            - name: ROUNDCUBEMAIL_SMTP_USER
              value: "%u"
            - name: ROUNDCUBEMAIL_SMTP_PASS
              value: "%p"
            - name: ROUNDCUBEMAIL_DB_DSNW
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 1
              memory: 500Mi
