apiVersion: v1
kind: ConfigMap
metadata:
    name: immich-values
    namespace: immich
data:
    values.yaml: ENC[AES256_GCM,data:cniZ2h2OKb76an9qI1rijVN7qpsd9DIqclq7GMIMqbEKfmWgY2l7YHxFFrFJACCxhYcZfAR/4X4zs0Zb0jMj85DPLJKl0WHzA/xSVIGxe9zG64qkrLq3+YCXvSvf/J2dsAvnc74it1CHNf/OmKyMOgXRNRQhiBb6AI9PtSyeVREaV9yWs00vuL8EscWhfwSR8LBp5SJ7UHJV46PNrtHOGEnzShhnlrg449IJTzzopRMgMol2bYJhR3y5V7MUVmfHpY5EuOc4bIP9n40oR43i1Y7qZgn6v5e74pVy5j3ylvSHcjLH1k6xPqik8ATpY3nffunu2ajVOmG83IRXwDUrsNwQ0g7z0ev/MCu8zzu57LcXJHosl2GJLFXPy4YFtzkeywHhh56yXh6OWnTJ5ID7FgKoMP4PH9B12F0buLYvQ4lV0kaG71jswItE/lhM/9unzEn/wiifmAvfu84BtV6IMmg/zUmyJp9tXaud0Kidigq+lVnvICdNmfmIDD4wpane50moZ2pSbPHFa5iyTP7qGWQhCzypyPrzFsmog66bwCxdGgbk9/4FoiP11fRyjcQLRWAH3dMfZ1MPwnLnRlBIMyBNEk55jKTtRJEQevK2vabDIZ2UmbWp5KqA+a4cnXvKF86yE0BYi52/Xcu4W9iyQP/pSWdSk5upqx+mw23ggpGEUHUp8LdeHtnwrHgk4F9ldLXYMJAnPaBuOTVzwT24Gs2XmQ/XapwjT7FhpcD/LEHUjTOpl9ZDHJn1AIojNk6n9WbaAXSHB9PeNXiInLtGi+Vdx3AhuoPeCWlHGP7z5gOHrR79spM2txuQtdxDvv9q9+uZTw9HBpeKrFgIRzO5uv/LftZcfb5+Reb1OiuFvc5xiaV3xNbd1qwLIuFHgVVrixYwyaTmBdy0ozDy0FOU3397KlYYce1h8WBMGML0aYjwGvaeBCVjQ3sU2kdZ3EaGoRD1uQA/8Ic6yY1jEAOtvHPmT2VBnalUkyHTyiVtfigMBtIiS0wr+DvuCzy3mSXBvAtJV1xTn4AF+sE6WvW4sWNeuPWYNuEWz9WXR+X214ZEsLBKSFzoCQUwwDnHcXA=,iv:8rfxu7fuv4rlKxkJFuxwderVrE5nYUcDrQ3//oXe9dU=,tag:x2/nTSpdxwysDAjD9JB44Q==,type:str]
sops:
    lastmodified: "2026-02-01T19:14:33Z"
    mac: ENC[AES256_GCM,data:byso4jqPI4FLmEl3ESi2QIzSAp6hl62E64FgmIZjeycgvMkoYfiGxCojc/8cXH5diGaDteN11FiBcgJ8JbubMkJWhYDrqWEHdSCKFUSijQNHr1ERxJTaxPy4yKsaBzSRAFNTM1BrYzANAINWd2asMYe15AU9A75P8F4cCT4a8q4=,iv:18xpDvscEZJxYT1WVGhtqOYlAmefqwd9sTizOFJmsP8=,tag:ArbReLH1SOLskQTBXY5sgQ==,type:str]
    pgp:
        - created_at: "2025-09-03T10:06:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D6rJQTzBUCVESAQdA3f8Jq1fIFg3WZJuCMhRb//Gn7Zku99MtWoe8e39YPxQw
            NTmgfeexkeTJwkial0fcLvon9hAqOVxBN+kArThyBofqxvqXm+1VJ5syGnmEmxLr
            0l4B2/veZjvWp9ubAK264ccqEhnlr1Mm0i+croE4Q5xg7MyEM80O3e5E6/HJWkyf
            pfWOQSi+zl5jEy7VCKBLG7LG87pZ0I8m1JPfcI8SxdOhc3BFzVcGzLHtx9pL16lY
            =N068
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2025-09-03T10:06:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAJDp/GskA6AzqMgcFv0EqGOgqX8YL42debcHwI8+srRgw
            WxA8bNKfJYvkvoGYkt3YfrV/nz+6ri/aYYHk8O4Nr+5cKNKet4N7wlro5xQyPmu4
            0l4BJ9j0Sh5ZQe9yAeX27FetbDPDZVXUzihhSrNbaNB3Cwi1y/0kAmibQxb4fCaY
            kSvOarg8zQbPLWA+kiatLzQ2yQH0RuWQKTO4x2mJ6QzxFL3N0Umz/EAp4MPUCxON
            =/CEp
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.10.2
