apiVersion: v1
kind: ConfigMap
metadata:
    name: immich-values
    namespace: immich
data:
    values.yaml: ENC[AES256_GCM,data:hFvSSVsh4NZLe2xRIhmzR051Lc0tJNacd0v2EfJz3seV0oO4Iak/q3Wo2a3Ia0DoN+hzCPETObVoDtozv3qiQ/NXr/3ITxqnOV+Pz4c8JAXgCeTgset+mVqZdaz4MMYvVG8cGwDSpfkk4v01Df33Ao9iAoXDgbD0OlWz0RKuMEBA4piSR8LtSjrqrATJPWjfvZAnpP2n6YN2IMVFGSynvfnr6YLlpZNXehxX2tLDo4FfeUyYB11dThAu5o7gNhXTQTUiGQKExWsEViACMlk7mee+BweKLxRM5epsjAE9a9/7iW2IPBnG96rpEsi3Gx4Kyafe6mieqVZAf970/Jf84gI0HP7WmukB94KsdxjKAN/aRJHIqStm3wIeoOBMkfg60Bzl7JMt+E4xMwhWBtCyzKCTOV2nVXjuWeUgjP2wCfQL5Sx1jh6GcHBOHRkHmGQb9X9NOkOWfH6JRtGNykNZFnJesyUrDlssAple+iyAPoXoZHFZtuYzhFuKAbCb9ytKF6mg7oGZapQKHJultH7yH+5VXCem321sNeo2Pp62vlda4leBn2LkJ99f+e6mkDqIutgg3KUvleiGl/wBSzWRQtPAGVx1uE00DoFpdF8uN3qVsipD1jzzKo0nIoRBOhIU11xnQGMp3EsVseRlLpEMdSTJmHtNu9imUpL2+Jfne6eSajFeDVYcTqcdeNindY0J9jaLix8LqJvf89A2ZJUiO2ltagSa2YdhGB97OWMtbklh8yE8X3w8aOFY/Ijo2QrdH5JpkuZzdPJPwF1B3rk9V12pMZd382ZMNPcKRinFAiyQCPnRFb1iUzktwxgHxVpH+crK9N2o3uvAgqAop42WPV86+Lqi0xa8+tGuAreL0w5VvRB9GUGkwGsa+1diRQDWfzkx9awaRG6zfPCChJhI+RHE8oX8bP8S1x9yQKznNNyM+ZVTUUjNyazri1HNYZd8bDtEO+tbP0Z1T1vvEOmdJPNNEjgoqeQJ79XdAHGKmgSGTp4HuRRIz3n2FMXUJOF74NLBm6FXET274NNereiwX+fbUtQ2QvDp5+ErFO+NarIN8KnZgRxpCoNt1PyOv3o=,iv:LduTBoUzxvwua6dagoNOj+MYSkc0EYt35Zz77Lt9Zzc=,tag:6jlnSAcC+u2mc51zfx0nfQ==,type:str]
sops:
    lastmodified: "2025-11-24T18:46:39Z"
    mac: ENC[AES256_GCM,data:1mN8Mv5dAF1xIfaIj3/r1lWrnUjZrgcbLjnrh2cDoXgdQI8a6NCOrh7Rq6BWTFsCTcdcTQPF+OIodoYWn/rO+dXltYrdT6bpnvb0VgjICPjCobJqEMatg4rH9InvHJeN+ovL079mmNylTf7ljMcbEQjJH+5OpuDngkMk7lq+WLg=,iv:WjKv4HDwlw4yPk6Qoexsatw2ByN/1+HoBjMASkoAmNE=,tag:GhxinaNn9KtWC/VEpp4DdA==,type:str]
    pgp:
        - created_at: "2025-09-03T10:06:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D6rJQTzBUCVESAQdA3f8Jq1fIFg3WZJuCMhRb//Gn7Zku99MtWoe8e39YPxQw
            NTmgfeexkeTJwkial0fcLvon9hAqOVxBN+kArThyBofqxvqXm+1VJ5syGnmEmxLr
            0l4B2/veZjvWp9ubAK264ccqEhnlr1Mm0i+croE4Q5xg7MyEM80O3e5E6/HJWkyf
            pfWOQSi+zl5jEy7VCKBLG7LG87pZ0I8m1JPfcI8SxdOhc3BFzVcGzLHtx9pL16lY
            =N068
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2025-09-03T10:06:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAJDp/GskA6AzqMgcFv0EqGOgqX8YL42debcHwI8+srRgw
            WxA8bNKfJYvkvoGYkt3YfrV/nz+6ri/aYYHk8O4Nr+5cKNKet4N7wlro5xQyPmu4
            0l4BJ9j0Sh5ZQe9yAeX27FetbDPDZVXUzihhSrNbaNB3Cwi1y/0kAmibQxb4fCaY
            kSvOarg8zQbPLWA+kiatLzQ2yQH0RuWQKTO4x2mJ6QzxFL3N0Umz/EAp4MPUCxON
            =/CEp
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.10.2
