apiVersion: v1
kind: ConfigMap
metadata:
    name: immich-values
    namespace: immich
data:
    values.yaml: ENC[AES256_GCM,data:MTD5S58AGLGfkHuBn9CpWoT+HciIEXLVaIagMeq1dt8re7Ql18PE/dm3ao8zoFCsZYeySjhsU60XWCNyxdULgvXyxDHr5T8a1aqj6UnEkPc33GoBdd1GOIXG2Y6s3M7nAF5gMRsyRfizpv21A8gsIjg4nv/LVUaOT58VWD9DlQhxy1K2j9Ymhmm25iuPtfMqYjnoFBz0SvZ3EFAvaFycF4VsQfoHPsxP1aZ8/bQ9/7BAePsAvlB68EZ/FBSVOt6WMlGudYtiMBJqpunyvU50IjId1PNDgFgk8DmqEAWn9oUubIzu+baArR9SyGT1KW/kkje2AJywBJAqMuw4+hcPNJgo9OONCln2YFviaEguBAAXzUf2DZC7jW1WT4TzgTNmE8gyXOIPXk4Spd5szTxzE5NW4YhUC36DJ7B9m/N7GhwR74WLszdGo3o3pET9XrErMKZfrL3mVp3ScCvX0sjcM86pkCro0rCjxMIANREmI9jJUZAaWGSdeo4GtQraqn5OV3/6MCGdri3M9fObe5sXGQA2VXyXCamqZeKxjrUpabSz5zJrgNf52ac/9aEJbxkhkJtMVAhUzxlkqvwYKjP6GuMU3WcjazoZ+2JbR0elmdvyZPxd6cVh4KsF8jERhpZ+UkTD8xlPAa51BXgfWZP+3mTUSGAs0YOPD2EAM66jDaUnQZGNWXkKuNFObOnAO9oJ8rK7lAS3y360YxIlM7LDKW3UW1C9QdMLiprI73UpNPF6kr4Q2ccmsCW0Op9bYKiL5l8hz03PHqO8zmQKyG7vJe1T/W/eJWFT4XCWsmNyot+dtaQ/1xEj9+iPtcnEW4KOln1CvHqDorc9AHaiyLqp6oZxHYdwNpSgbhfEpcUoesE03h8xuyfX8g4pdUrOLGdmkCqnwh/WzqvOqSgI4uKmKSoWwR306RoNLtn9olKf5qsekpMxfYBU+oVKlZkJ85fbUQQ8vuGI0/EZas9AyqtlmxLvxsxKCOiAUPluAUw4KXyPeKczp8HERclQzV5dV/i5KqFVNvYXNvH6+OmcttIYHH/vlHu/9zlDr7TlURCjrlLZFR3qfFzCbfi7rfWWQ7I=,iv:nVaW/kZNUImF4sOSCA5gfvWTX7mRAkkMxtUzsb7uC4M=,tag:W22cXeveZFP9KiLE7uKPLw==,type:str]
sops:
    lastmodified: "2025-11-02T15:25:57Z"
    mac: ENC[AES256_GCM,data:FwPwh5vPoVVku53LktlnfFhMOlLZc7Yce0hjMnnyZrdXKeGnBr3iLtSxzNDszPisylxvevspo0PQPuHZB/MHCzeUzJkSMegI5sMABONG5jZ/66pZLOrVJXsgmxp4Vx/ZBmkXHLAOmyqJJ/x6nviqicHsVQaa12d4CShiK1lpzyI=,iv:Mc2E+FkCtw4HtRrz3jPNdEe+KVM4RrAtoT6NwnVs/E4=,tag:yBCCLVjX6Qnq6JmG1a45zw==,type:str]
    pgp:
        - created_at: "2025-09-03T10:06:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D6rJQTzBUCVESAQdA3f8Jq1fIFg3WZJuCMhRb//Gn7Zku99MtWoe8e39YPxQw
            NTmgfeexkeTJwkial0fcLvon9hAqOVxBN+kArThyBofqxvqXm+1VJ5syGnmEmxLr
            0l4B2/veZjvWp9ubAK264ccqEhnlr1Mm0i+croE4Q5xg7MyEM80O3e5E6/HJWkyf
            pfWOQSi+zl5jEy7VCKBLG7LG87pZ0I8m1JPfcI8SxdOhc3BFzVcGzLHtx9pL16lY
            =N068
            -----END PGP MESSAGE-----
          fp: 459895EB0A5F446D3831E99F95F6A162E4A71B06
        - created_at: "2025-09-03T10:06:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8q6e3Tem1ZoSAQdAJDp/GskA6AzqMgcFv0EqGOgqX8YL42debcHwI8+srRgw
            WxA8bNKfJYvkvoGYkt3YfrV/nz+6ri/aYYHk8O4Nr+5cKNKet4N7wlro5xQyPmu4
            0l4BJ9j0Sh5ZQe9yAeX27FetbDPDZVXUzihhSrNbaNB3Cwi1y/0kAmibQxb4fCaY
            kSvOarg8zQbPLWA+kiatLzQ2yQH0RuWQKTO4x2mJ6QzxFL3N0Umz/EAp4MPUCxON
            =/CEp
            -----END PGP MESSAGE-----
          fp: DF7F5D62376A57228F35FE4C665F8C5B8E0732E5
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.10.2
