apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberchef
  labels:
    app: cyberchef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberchef
  template:
    metadata:
      labels:
        app: cyberchef
    spec:
      containers:
        - name: cyberchef
          image: ghcr.io/gchq/cyberchef:10.22.0@sha256:8b7a9a8002c74ec1c473c21ce38503f179fe91f9c5442d68c185ba26a0415617
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 0m
              memory: 0Mi
            limits:
              cpu: 200m
              memory: 100Mi
